version: "3"

networks:
  dashboard-net:

services:
  nginx-dev:
    image: nginx:alpine
    container_name: dashboard-nginx-dev
    restart: always
    volumes:
      - ./resources/nginx-dev-server.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
    networks:
      - dashboard-net
    depends_on:
      - dashboard-ui
      - dashboard-server

  dashboard-ui:
    build:
      context: ../dashboard-ui
      args:
        PUBLIC_URL: /dev
        CONFIG_PATH: public/configs/dev-server/config.js
    image: dashboard-ui
    container_name: dashboard-ui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dashboard-net

  dashboard-server:
    container_name: dashboard-graphql
    image: dashboard-graphql
    restart: always
    volumes:
      - ../dashboard-ui/public/configs/dev-server/graphql-config.js:/usr/src/app/config.js
      - $HOME/.aws/:/root/.aws/:ro
    ports:
      - "9100:9100"
    networks:
      - dashboard-net
    depends_on:
      - dashboard-mongo
    environment:
      NODE_OPTIONS: "--max-old-space-size=16384"
      NODE_ENV: "production"

  dashboard-mongo:
    image: mongo
    restart: always
    container_name: dashboard-mongo
    command: --port 27030
    networks:
      - dashboard-net
    environment:
      - MONGO_INITDB_DATABASE=dashboard
      - MONGO_INITDB_ROOT_USERNAME=dashroot
      - MONGO_INITDB_ROOT_PASSWORD=dashr00tp@ssw0rd
    volumes:
      - ./resources/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    expose:
      - "27030"